[package]
name = "imag"
version = "0.10.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

build = "build.rs"

[build-dependencies]
clap = ">=2.16.1"
libimagrt       = { version = "0.10.0", path = "../../../lib/core/libimagrt" }
libimagerror    = { version = "0.10.0", path = "../../../lib/core/libimagerror" }
libimagstore    = { version = "0.10.0", path = "../../../lib/core/libimagstore" }
libimagentrytag = { version = "0.10.0", path = "../../../lib/entry/libimagentrytag" }
libimagutil     = { version = "0.10.0", path = "../../../lib/etc/libimagutil" }
log             = "0.4.6"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
walkdir = "2"
log = "0.4.6"
toml = "0.4"
toml-query = "0.8"

libimagerror = { version = "0.10.0", path = "../../../lib/core/libimagerror" }
libimagstore = { version = "0.10.0", path = "../../../lib/core/libimagstore" }

[dependencies.clap]
version = "^2.29"
default-features = false
features = ["suggestions", "color", "wrap_help"]

[dependencies.libimagrt]
version  = "0.10.0"
path     = "../../../lib/core/libimagrt"
features = ["pub_logging_initialization"]

