[package]
name = "imag-mail"
version = "0.10.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-mail command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://imag-pim.org/doc/"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

build = "../../../build.rs"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
log = "0.4.6"
failure = "0.1"
indoc = "0.3"

libimagrt       = { version = "0.10.0", path = "../../../lib/core/libimagrt" }
libimagstore    = { version = "0.10.0", path = "../../../lib/core/libimagstore" }
libimagerror    = { version = "0.10.0", path = "../../../lib/core/libimagerror" }
libimagmail     = { version = "0.10.0", path = "../../../lib/domain/libimagmail" }
libimagutil     = { version = "0.10.0", path = "../../../lib/etc/libimagutil" }
libimagentryref = { version = "0.10.0", path = "../../../lib/entry/libimagentryref" }

[dependencies.clap]
version = "^2.29"
default-features = false
features = ["color", "suggestions", "wrap_help"]

[dependencies.toml-query]
version = "0.8"
default-features = false
features = ["typed"]

